/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jasontjia.kotlin.cp1

fun BilPrima(
    x: Int, divided: Int = 2
):
        Boolean {
    if (x < 2)
        return false
    if (x == 2 || x == 3)
        return true
    if (x % divided == 0)
        return false
    if (divided * divided > x)
        return true
    return BilPrima(x, divided + 1)
}


fun main(args: Array<String>) {
    val prima = readLine()!!.toInt()
    repeat(prima) {
        val x = readLine()!!.toInt()
        val result = if (BilPrima(x)) "Bilangan Prima"
        else "Bukan Bilangan Prima"
        println("Kasus ${it+1}: $result")
    }
}